apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api
  team: devops

commonAnnotations:
  note: "This is an Production deployment"

resources:
  - ns.yaml
  - ../../base

patches:
  # in-line
  - target:
      name: svc-public-api
    patch: |
      - op: add
        path: /spec/type
        value: ClusterIP

    
  # yaml file
  - target:
      name: public-api
      kind: Deployment
    path: deploy-patch.yaml

  - target:
      name: cm-private-api
    path: cm-patch.yaml

  - target:
      name: public-api
      kind: Ingress
    path: ingress-patch.yaml

images: 
  - name: KUSTOMIZE-DEFINED
    newName: hsolicha/kubelabs_publicapi2
    newTag: 1.0.0