apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api
  team: devops

commonAnnotations:
  note: This is an Production deployment

resources:
- ns.yaml
- ../../base

  # in-line

    
  # yaml file


patches:
- patch: |
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    name: svc-public-api
- path: deploy-patch.yaml
  target:
    kind: Deployment
    name: public-api
- path: cm-patch.yaml
  target:
    name: cm-private-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: public-api

images:
- name: KUSTOMIZE-DEFINED
  newName: hsolicha/kubelabs_publicapi2
  newTag: 2.0.0
