apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api-stage
  team: devops

commonAnnotations:
  note: This is an STAGE deployment

resources:
- ns.yaml
- ../../base

patchesStrategicMerge:
- deploy-merge.yaml


  # in-line

    

  # yaml file

patches:
- patch: |
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    name: svc-public-api
- path: cm-patch.yaml
  target:
    name: cm-private-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: public-api




images:
- name: KUSTOMIZE-DEFINED
  newName: hsolicha/kubelabs_publicapi2
  newTag: 5.0.0
