apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-public-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: public-stage
    server: 'https://kubernetes.default.svc'
  source:
    path: public-api/overlays/stage
    repoURL: 'git@github.com:solischaconhenry/ops.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true